language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6.1'
  - '6'
before_script:
  - npm install -g bower polymer-cli
  - pushd public && bower install && popd
script:
  - xvfb-run npm test
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}