language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '7.4'
  - '7'
before_script:
  - npm install -g bower polymer-cli
  - bower install --config.cwd=./public
script:
  - xvfb-run npm test
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}